In [30]:
import pandas as pd

In [31]:
file_path = "Messy_Employee_dataset.csv"

df = pd.read_csv(file_path, encoding="utf-8", sep=",", dtype={
    "employee_id": "string",
    "age": "float",
    "salary":"float"
}
)

df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [32]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

np.int64(0)

In [33]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique()[:10])

Employee_ID
['EMP1000' 'EMP1001' 'EMP1002' 'EMP1003' 'EMP1004' 'EMP1005' 'EMP1006'
 'EMP1007' 'EMP1008' 'EMP1009']

First_Name
['Bob' 'Alice' 'Eva' 'Frank' 'Charlie' 'David' 'Heidi' 'Grace']

Last_Name
['Davis' 'Brown' 'Jones' 'Williams' 'Garcia' 'Johnson' 'Miller' 'Smith']

Age
[25. nan 40. 30. 35.]

Department_Region
['DevOps-California' 'Finance-Texas' 'Admin-Nevada' 'Cloud Tech-Florida'
 'Sales-Texas' 'DevOps-New York' 'Cloud Tech-New York' 'HR-New York'
 'Finance-California' 'Sales-Florida']

Status
['Active' 'Pending' 'Inactive']

Join_Date
['4/2/2021' '7/10/2020' '12/7/2023' '11/27/2021' '1/5/2022' '6/10/2020'
 '4/3/2020' '7/17/2022' '12/8/2023' '8/4/2022']

Salary
[ 59767.65  65304.66  88145.9   69450.99 109324.61  88642.84  96288.43
  94497.91 115565.82  76561.88]

Email
['bob.davis@example.com' 'bob.brown@example.com' 'alice.jones@example.com'
 'eva.davis@example.com' 'frank.williams@example.com'
 'alice.garcia@example.com' 'frank.jones@example.com'
 'bob.jones@example.com' 'frank.davis@example.com'
 'charlie.johnson@example.com']

Phone
[-1651623197 -1898471390 -5596363211 -3476490784 -1586734256 -5409003485
 -4518376063 -4134327559 -4177656123 -8156985699]

Performance_Score
['Average' 'Excellent' 'Good' 'Poor']

Remote_Work
[ True False]

In [34]:
df.columns = df.columns.str.strip().str.lower()

In [35]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce")

In [36]:
df["salary"] = (
    df["salary"]
    .astype(str)
    .str.replace(",","")
    .replace("N/A", None)
)

df["salary"] = pd.to_numeric(df["salary"], errors="coerce")

In [37]:
df[["depertment", "region"]] = df["department_region"].str.split("-", expand=True)

In [38]:
df["status"] = df["status"].str.strip().str.lower()

df["performance_score"] = df["performance_score"].str.strip().str.lower()

In [39]:
df["age"] = df["age"].fillna(df["age"].median())

df["salary"] = df["salary"].fillna(df["age"].median())

In [40]:
df = df.drop_duplicates()

In [41]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        1020 non-null   object
 1   first_name         1020 non-null   object
 2   last_name          1020 non-null   object
 3   age                1020 non-null   float64
 4   department_region  1020 non-null   object
 5   status             1020 non-null   object
 6   join_date          1020 non-null   datetime64[ns]
 7   salary             1020 non-null   float64
 8   email              1020 non-null   object
 9   phone              1020 non-null   int64
 10  performance_score  1020 non-null   object
 11  remote_work        1020 non-null   bool
 12  depertment         1020 non-null   object
 13  region             1020 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(9)
memory usage: 104.7+ KB

               age                      join_date         salary         phone
count  1020.000000                           1020    1020.000000  1.020000e+03
mean     31.970588  2022-07-26 12:53:38.823529472   83152.113892 -4.942253e+09
min      25.000000            2020-01-01 00:00:00      30.000000 -9.994973e+09
25%      30.000000            2021-04-12 06:00:00   67498.347500 -7.341992e+09
50%      30.000000            2022-08-09 12:00:00   84711.750000 -4.943997e+09
75%      35.000000            2023-10-31 12:00:00  100372.662500 -2.520391e+09
max      40.000000            2024-12-29 00:00:00  119971.650000 -3.896086e+06
std       5.136901                            NaN   23501.379644  2.817326e+09

In [43]:
df.to_csv("Cleaned_employee_dataset.csv", index=False)